apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app-demo
  labels:
    app: java-app-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-app-demo
  template:
    metadata:
      labels:
        app: java-app-demo
    spec:
      containers:
      - name: java-app
        image: varaprasad365/harness-app:jar-app
        ports:
        - containerPort: 8080
